feature: single extension
abak-press/findit pull request #6
Opened 2017-03-30 13:04 UTC by deniskorobicyn

Применимо для файндеров которые возвращают лишь одну запись по заданным параметрам.

2017-03-30 13:04 UTC, deniskorobicyn commented
@Napolskih, можно тут дрон активировать, пожалуйста)

2017-03-30 13:15 UTC, bibendi requested changes
большая дубликация кода в Collection,
давай в него инклуд Single

2017-03-30 15:37 UTC, Napolskih commented on lib/findit/single.rb
> +#      @post = PostFinder.new(current_user, query: 'some desc')
.call

2017-03-30 15:37 UTC, Napolskih approved these changes

2017-03-31 09:55 UTC, deniskorobicyn commented on lib/findit/single.rb
> +#      @post = PostFinder.new(current_user, query: 'some desc')
не, тут как раз call не нужен, иначе кеш во вьюхе бессмысленен

поправил во вьюхе ниже, там бред написан был

2017-03-31 09:56 UTC, bibendi approved these changes

2017-03-31 09:56 UTC, Napolskih approved these changes

2017-03-31 12:07 UTC, merged