feature: cache extension
abak-press/findit pull request #7
Opened 2017-03-31 12:20 UTC by deniskorobicyn

Нужно для файндеров которые вызываются в куче мест, но не связанны с вьюхами, например, вызываются в других файндерах.

2017-03-31 12:21 UTC, apress-hound commented on spec/findit_spec.rb
> +          new_post = Post.create(user_id: user.id, text: 'Some post')
Useless assignment to variable - new_post.

2017-03-31 12:21 UTC, apress-hound commented on lib/findit/cache.rb
> +      if !defined?(cache?) || cache?
Use the return of the conditional for variable assignment and comparison.

2017-03-31 12:24 UTC, Napolskih commented
В рамках какой задачи и для чего все это счастье?
Нет задачи - нет работы.

2017-03-31 12:28 UTC, bibendi approved these changes

2017-03-31 12:33 UTC, deniskorobicyn commented
опенсурсный гем, был не уверен что в него стоит класть ссылки на задачи -
https://jira.railsc.ru/browse/PC4-19397

описание там конечно очень понятное..

В крации проблема такая:
Есть презентер, при решении задачи фронта (в описании задачи) он станет вызываться в двух очень "далеких" друг от друга местах (одно в  партиале в yield, другое в content_for)  на одной странице, но рисовать разные вьюхи, чтобы снизить количество запросов в базу эти презентером решили закешировать файндеры в нем, ссылка на сам презентер - 
https://github.com/abak-press/pulscen/blob/develop/app/presenters/addresses_presenter.rb#L18

2017-03-31 12:33 UTC, deniskorobicyn commented
предыдущий мой ПР был также частью этой задачи

2017-03-31 12:55 UTC, Napolskih commented on README.md
> +    @no_cache = !options[:no_cache]
Почему тут инверсия?

2017-03-31 12:55 UTC, Napolskih commented on README.md
> +    @no_cache = !options[:no_cache]
Ну и печалька что нет базового класса файндера, там бы можно было стандартные опции обрабатывать, а не копипастить по прикладному коду.

2017-03-31 13:09 UTC, Napolskih reviewed
> Есть презентер, при решении задачи фронта (в описании задачи) он станет вызываться в двух очень "далеких" друг от друга местах (одно в партиале в yield, другое в content_for) на одной странице, но будет рисовать разные вьюхи, чтобы снизить количество запросов в базу этим презентером решили закешировать файндеры в нем

Я так и не понял почему раньше было два запроса? При выводе первой вьюхи разве результат не закешируется?

2017-03-31 13:09 UTC, Napolskih commented on README.md
> +  end
Почему один пост то?

2017-03-31 13:09 UTC, Napolskih commented on README.md
> +  end
Или синг надо

2017-04-01 05:18 UTC, deniskorobicyn commented on README.md
> +    @no_cache = !options[:no_cache]
Инверсия не нужна, сделаю нормально.

хмм, думаю, можно без базового класса обойтись, а просто проверять был ли вызов self.сlass.cache? в call.

2017-04-01 05:24 UTC, deniskorobicyn commented on README.md
> +  end
Cache по умолчанию ведет себя как Single, если вызвать `include Collection` перед `include Cache` будет Collection.

Тут мне не очень нравиться зависимость порядка инклудов, подумаю еще, может получиться сделать их независимыми.

2017-04-01 05:24 UTC, deniskorobicyn commented
> Я так и не понял почему раньше было два запроса?

Станет в два раза  больше запросов) Тк один и тот же презентер с тремя разными файндерами внутри будем вызываться два раза. 

> При выводе первой вьюхи разве результат не закешируется?

В этом то и проблема, вьюхи у двух вызовов презентера будут разные.

2017-04-01 05:31 UTC, deniskorobicyn commented on README.md
> +    @no_cache = !options[:no_cache]
> а просто проверять был ли вызов self.сlass.cache? в call.

А стоп, я же уже это сделал))
Там же проверяется defined?(:cache), те опция не обязательная, опишу это в доке.

2017-04-01 06:22 UTC, deniskorobicyn commented on README.md
> +    @no_cache = !options[:no_cache]
хотя вот счас еще раз подумал, мы наверное захотим во многих файндерах иногда выключать кеш динамичеси....

можно сделать немного иначе:
сделать метод DSL optional_cache? - без агргументов, который будет проверять наличие переменной `@cache`, а ее уже устанавливать у удобом для файндера месте, например:

```ruby
class CachedPostsFinder
  include Findit::Cache
  
  optional_cache

  cache_key do
    user.id
  end

  cache_options do
    {expire_in: 30.minutes}
  end

  def initialize(user, options = {})
    @user = usre
    @cache = options.fetch(:cache, true)
  end

  private
  
  def find
    Post.where(user: user)
  end
end
```

2017-04-01 06:35 UTC, Napolskih commented on README.md
> +    @no_cache = !options[:no_cache]
Ну об этом и речь - реализовывать опцию в каждом файндера.

2017-04-01 06:36 UTC, Napolskih commented on README.md
> +  end
Просто странно где то нужен инклуд синг, а где то нет.

2017-04-01 06:36 UTC, Napolskih commented on README.md
> +  end
Почему кеш ведет себя как синг? Для кого это очевидно?

2017-04-01 06:38 UTC, Napolskih commented
Я может тупой, но я не понимаю почему вызов одного и того же файндера с одинаковыми параметрами и кеш ключами порождает два запроса?
Объясни плиз на простом примере из псевдокода.

2017-04-01 07:04 UTC, deniskorobicyn commented
Да я видимо как-то плохо объясняю))
Есть презентер AddressesPresenter (оцензурено для опенсорса 😄 )
```ruby
class AddressesPresenter
  def my_addresses(param:)
     @addresses = AddressFinder.new(current_user)
     if param
       view.safe_concat('view_1')
     else
       view.safe_concat('view_2')
     end
  end
end
```
и его вызовы, оба партиала рендрятся на одной странице
```ruby
# _main_view.html.haml
 ...
cache(some_key) do
  = presenter :addresses, :my_address, param: true
 ...

#  _right_column.html.haml
cache(some other key) do
  = present :addresses, my_address, param: false
```

Тут вроде бы все хорошо, но при первом рендринге страницы, когда нет кеша вьюх, будет создание двух объектов AddressesFinder и, следовательно, каждый из них сделает запрос в базу, итого будет два одинаковых запроса для получения одних и тех же данных - первый в main_view, второй в right_column.

В примере вроде бы решение видно сразу - записать переменную `@addresses` в контроллере, но в нашем конкретном случае, файндеров несколько, вьюхи в очень разных местах параметры презентера формируються походу рендрига вьюх, чтобы передать значение в презентрер, придется переписать кучу кода. Поэтому решили сделать кеш файндеров.

2017-04-02 12:19 UTC, Napolskih commented
понятно, потому что кеш сейчас весь снаружи и ключи формируются не только на основании параметров файндера. щас ты сделал возможным иметь внутри файндера иметь кеш.

2017-04-03 05:42 UTC, deniskorobicyn commented on README.md
> +    @no_cache = !options[:no_cache]
может сделаем как в интеракторах?

```ruby
class CacheFinder
  include Findit::Finder
  include Findit::Cache

  arguments :user

  def find
    Post.where(user: user)
  end
end

# и тогда вызов
# возвращает вызов метода find, cache: true - по умолчанию
posts = CachedFinder.find(user: user, cache: true)
``` 

сама реализация тогда  примерно - 

```ruby
module Finder
  module ClassMethods
    def arguments(*args)
      delegate args, to: :context
    end

    def find(*args)
      context = Findit::Context.new(args)
      new(context)
    end
  end

  included do
    attr_reader :context
  end

  def initialize(context)
    @context = context
  end
end
```

тогда  расширение cache сможет проверять context на нужный параметер

Единственный минус - что придется обратную совместимость текущих файндеров поломать...

2017-04-03 05:53 UTC, Napolskih commented on README.md
> +    @no_cache = !options[:no_cache]
ну композиция - это хорошо.
надо сделать что бы старые файндеры работали и новые по-новому можно было писать.
так лучше чем каждый раз конструкторы реализовывать.

2017-04-03 06:19 UTC, deniskorobicyn commented on README.md
> +    @no_cache = !options[:no_cache]
счас посоветовались с Мишей, решили проще пока сделать, чтобу задачу не растягивать - 

```
class CachedFinder
  include Findit::Cache
  include Findit::Collections

  # без лишних опций
  def initialize(user)
    @user = user
  end

  cache_key { user.id }
  cache_options { {expire_in: 30.minutes} }

  def find
    Post.where(user_id: @user.id)
  end
end

# если хотим выключить кеш
CachedFinder.new(user).without_cache.call
```

2017-04-03 06:22 UTC, Napolskih commented on README.md
> +    @no_cache = !options[:no_cache]
ok

2017-04-03 07:28 UTC, deniskorobicyn commented
:up: @bibendi, @Napolskih 
 - убрал метод `cache?`, добавил метод `without_cache` для инстанса
 - добавил тестов на `Cache`, `Collections` вместе

2017-04-03 07:33 UTC, Napolskih approved these changes

2017-04-03 07:51 UTC, bibendi requested changes

2017-04-03 07:51 UTC, bibendi commented on lib/findit/cache.rb
> +    include ::Findit::Single
вот это неправильно же. вместе с кешем не должен приезжать Single

```ruby
class SomeFinder
  include Findit::Cache
  include Findit::Collections
```

и Single приехал два раза.

считаю, что Single должен приезжать либо явно, либо из Collections
Cache он сам по себе. Он лишь добавляют прослойку для `call`.

если по простому оставить, то инклудить Cache в финдер надо всегда после Single/Collections, чтобы перекрыть call.

если по сложному, то без перекрытия call, юзать AS::Callbacks, и в before_find извлекать данные из кеша.

2017-04-03 07:51 UTC, bibendi commented on lib/findit/cache.rb
> +    def find
это здесь не нужно

2017-04-03 10:18 UTC, deniskorobicyn commented
:up: @bibendi, сделал Cache расширение через  AS::Callback

2017-04-03 10:41 UTC, bibendi approved these changes

2017-04-03 10:41 UTC, bibendi commented on README.md
> +  include Findit::Cache
здесь надо инклуд

2017-04-03 11:14 UTC, merged